[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Josh Braun"
authors = [{name = "Josh Braun", email = "bbraunj@gmail.com"}]
dynamic = ["version", "description"]
